name: Generate GitHub Metrics

on:
  schedule:
    - cron: '0 */2 * * *' # Schedule to run every 2 hours
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (e.g., production, staging)'
        required: true
        default: 'production'
      metrics_tag:
        description: 'Metrics version tag or branch'
        required: false
        default: 'v3.34'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      # Install required dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker jq

      # Output context for debugging
      - name: Debug Context
        run: |
          echo "Workflow triggered by: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Environment: ${{ inputs.environment }}"
          echo "Metrics Tag: ${{ inputs.metrics_tag }}"

      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Metrics embed
      - name: Metrics Embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use PAT for enhanced access
          base: repositories
          repositories: 100
          user: ${{ github.actor }}
