name: Generate GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Schedule to run every 2 hours
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (e.g., production, staging)'
        required: true
        default: 'production'
      metrics_tag:
        description: 'Metrics version tag or branch'
        required: false
        default: 'v3.34'

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      # Install required dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      # Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Metrics Embed
      - name: Metrics Embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use PAT for enhanced access
          repositories: 100
                    # Options
          user: cstannahill
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: America/Chicago
          
          # Plugins
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          plugin_lines: yes
          
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          
          plugin_stargazers: yes
          
